# finalize.ps1
# Copies MzaTunerClone_Renamed -> MzaTunerClone_Final, then:
#   1. renames key files based on the role we identified
#   2. patches csproj: HintPath, removes [SuppressIldasm], updates Compile
#      Include to point at renamed files
#   3. removes anti-IL-DASM and module-attribute hooks
#   4. writes a small reference table FILE_RENAMES.md

param(
    [string]$SourceDir = "MzaTunerClone_Renamed",
    [string]$OutDir    = "MzaTunerClone_Final"
)

$ErrorActionPreference = "Stop"
if (-not (Test-Path $SourceDir)) { Write-Error "Missing $SourceDir"; exit 1 }
if (Test-Path $OutDir) { Remove-Item -Recurse -Force $OutDir }

Write-Host "[*] Copying $SourceDir -> $OutDir"
Copy-Item -Recurse -LiteralPath $SourceDir -Destination $OutDir
$root = (Resolve-Path $OutDir).Path

# -------- File rename table --------
# Old (relative to OutDir) -> New
$renames = @{
    'MZA_TUNER_FLASH_2026.3.cs'  = 'Form3_AcgEcuToBin.cs'        # Form_4 (RID 4)
    'MZA_TUNER_FLASH_2026.7.cs'  = 'Form4_XdfAdxBreaker.cs'      # Form_8 (RID 8)
    'MZA_TUNER_FLASH_2026.8.cs'  = 'Form5_OpenPassword.cs'       # Form_9 (RID 9)
    'MZA_TUNER_FLASH_2026.9.cs'  = 'Form_EepromTool.cs'          # Form_A (RID 10)
    'MZA_TUNER_FLASH_2026.10.cs' = 'License_Secrets.cs'          # license constants
    'MZA_TUNER_FLASH_2026.11.cs' = 'Form_LicenseKey.cs'          # License Key UI
    'MZA_TUNER_FLASH_2026.38.cs' = 'NetworkClient.cs'            # http calls (probable)
    'MZA_TUNER_FLASH_2026.39.cs' = 'Form_Update.cs'              # other Form (RID 245)
    'MZA_TUNER_FLASH_2026.40.cs' = 'AssemblyInfo_Extras.cs'
    'MZA_TUNER_FLASH_2026\.Designer.cs'   = 'Form3_AcgEcuToBin.Designer.cs'
    'MZA_TUNER_FLASH_2026\.Designer.2.cs' = 'Form4_XdfAdxBreaker.Designer.cs'
    'MZA_TUNER_FLASH_2026\.Designer.3.cs' = 'Form5_OpenPassword.Designer.cs'
    'MZA_TUNER_FLASH_2026\.Designer.4.cs' = 'Form_EepromTool.Designer.cs'
    'MZA_TUNER_FLASH_2026\.Designer.5.cs' = 'Form_LicenseKey.Designer.cs'
    'MZA_TUNER_FLASH_2026\.Designer.6.cs' = 'Form_Update.Designer.cs'
}

$mdLines = @()
$mdLines += "# File renames"
$mdLines += ""
$mdLines += "Mapping of file names from ``MzaTunerClone_Renamed`` to ``MzaTunerClone_Final``."
$mdLines += "Generated by ``tools\finalize.ps1``."
$mdLines += ""
$mdLines += "| Old | New | Class |"
$mdLines += "|---|---|---|"

# Apply renames at the top level (not the subfolder)
foreach ($kv in $renames.GetEnumerator()) {
    $oldPath = Join-Path $root $kv.Key
    $newName = $kv.Value
    $newPath = Join-Path $root $newName
    if (Test-Path -LiteralPath $oldPath) {
        Move-Item -LiteralPath $oldPath -Destination $newPath -Force
        Write-Host "    renamed  $($kv.Key)  ->  $newName"
        $mdLines += "| ``$($kv.Key)`` | ``$newName`` | (see CLASS_INDEX.md) |"
    }
}

# -------- patch csproj --------
$csproj = Join-Path $root "MZA_TUNER_FLASH_2026\MZA_TUNER_FLASH_2026.csproj"
if (Test-Path $csproj) {
    Write-Host "[*] Patching csproj"
    $xml = Get-Content $csproj -Raw -Encoding UTF8

    # 1. HintPath - point to C:\MZATUNER\FTD2XX_NET.dll
    $xml = $xml -replace '<HintPath>[^<]+FTD2XX_NET\.dll</HintPath>', '<HintPath>C:\MZATUNER\FTD2XX_NET.dll</HintPath>'

    # 2. Update Compile Includes for renamed files
    foreach ($kv in $renames.GetEnumerator()) {
        $oldName = $kv.Key
        $newName = $kv.Value
        # The csproj uses paths like  ..\MZA_TUNER_FLASH_2026.3.cs
        # The Designer files are like  .Designer.2.cs
        $oldRel  = "..\\$oldName"
        $newRel  = "..\\$newName"
        $xml = $xml.Replace($oldRel, $newRel)
        # also direct-path designer
        $xml = $xml.Replace($oldName, $newName)
    }

    # 3. StartupObject is currently the obfuscated entry-point class - leave it
    #    but commented for the user to update once they identify it.

    [System.IO.File]::WriteAllText($csproj, $xml, (New-Object System.Text.UTF8Encoding($false)))
    Write-Host "    patched   $csproj"
}

# -------- patch AssemblyInfo --------
$asmInfo = Join-Path $root "MZA_TUNER_FLASH_2026\Properties\AssemblyInfo.cs"
if (Test-Path $asmInfo) {
    Write-Host "[*] Patching AssemblyInfo.cs"
    $info = Get-Content $asmInfo -Raw -Encoding UTF8
    $info = $info -replace '\[assembly:\s*SuppressIldasm\][^\r\n]*', '// [assembly: SuppressIldasm]   // disabled by deobfuscator'
    $info = $info -replace '\[module:\s*\\u1680\([^\)]*\)\][^\r\n]*', '// [module: <Obfuscar attr>]   // disabled by deobfuscator'
    [System.IO.File]::WriteAllText($asmInfo, $info, (New-Object System.Text.UTF8Encoding($false)))
}

# -------- write FILE_RENAMES.md --------
$mdPath = Join-Path $root "FILE_RENAMES.md"
[System.IO.File]::WriteAllText($mdPath, ($mdLines -join [Environment]::NewLine), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "[+] Wrote $mdPath"

Write-Host "[+] Output: $root"
